// <auto-generated />
using System;
using Client.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Client.Migrations
{
    [DbContext(typeof(DTSMiniProjectContext))]
    [Migration("20221012172201_hh")]
    partial class hh
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Client.Models.Divisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnggaraanTetap")
                        .HasColumnType("int");

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Divisi");
                });

            modelBuilder.Entity("Client.Models.Pengadaan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IdBarang")
                        .HasColumnType("int");

                    b.Property<int?>("IdDivisi")
                        .HasColumnType("int");

                    b.Property<int?>("IdStatus")
                        .HasColumnType("int");

                    b.Property<int?>("IdSupplier")
                        .HasColumnType("int");

                    b.Property<int?>("Kuantitas")
                        .HasColumnType("int");

                    b.Property<int?>("Totals")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdBarang");

                    b.HasIndex("IdDivisi");

                    b.HasIndex("IdStatus");

                    b.HasIndex("IdSupplier");

                    b.ToTable("Pengadaan");
                });

            modelBuilder.Entity("Client.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HargaProduct")
                        .HasColumnType("int");

                    b.Property<int?>("IdSatuan")
                        .HasColumnType("int");

                    b.Property<int?>("IdSupplier")
                        .HasColumnType("int");

                    b.Property<string>("NamaProduk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StockProduct")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdSatuan");

                    b.HasIndex("IdSupplier");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Client.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Client.Models.Satuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Satuan");
                });

            modelBuilder.Entity("Client.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Client.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telepon")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("Client.Models.Pengadaan", b =>
                {
                    b.HasOne("Client.Models.Product", "IdBarangNavigation")
                        .WithMany()
                        .HasForeignKey("IdBarang");

                    b.HasOne("Client.Models.Divisi", "IdDivisiNavigation")
                        .WithMany()
                        .HasForeignKey("IdDivisi");

                    b.HasOne("Client.Models.Supplier", "IdSupplierNavigation")
                        .WithMany()
                        .HasForeignKey("IdStatus");

                    b.HasOne("Client.Models.Status", "IdStatusNavigation")
                        .WithMany()
                        .HasForeignKey("IdSupplier");
                });

            modelBuilder.Entity("Client.Models.Product", b =>
                {
                    b.HasOne("Client.Models.Satuan", "IdSatuanNavigation")
                        .WithMany()
                        .HasForeignKey("IdSatuan");

                    b.HasOne("Client.Models.Supplier", "IdSupplierNavigation")
                        .WithMany()
                        .HasForeignKey("IdSupplier");
                });
#pragma warning restore 612, 618
        }
    }
}
